title: Any blog
logo: https://avatars.githubusercontent.com/u/32850432?v=4
description: Blog about trivial things. LOL!!!
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM