minimal_mistakes_skin: "air"
title: Any blog
logo: https://avatars.githubusercontent.com/u/32850432?v=4
description: Blog about trivial things. LOL!!!
show_downloads: false
markdown: kramdown
mathjax: true
kramdown:
  input: GFM  